package com.mycompany.views;

import com.mycompany.ilib.DAOaccesorio_imple;
import com.mycompany.interfaces.DAOaccesorio;

public class Upaccesorio extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.models.Accesorio bookEdition;

    public Upaccesorio() {
        initComponents();
        InitStyles();
    }

    public Upaccesorio(com.mycompany.models.Accesorio accesorio) {
        initComponents();
        isEdition = true;
        bookEdition = accesorio;
        InitStyles();
    }

    private void InitStyles() {

        if (isEdition) {
        C_modelo.setText("Editar ficha");
        button.setText("Guardar");

        if (bookEdition != null) {
            nombre_A.setText(String.valueOf(bookEdition.getNombre_accesorio()));
            C_modelo.setText(bookEdition.getCodigo_modelo());
            stock_L.setText(String.valueOf(bookEdition.getStock_accesorio()));       
            jTextField1.setText(String.valueOf(bookEdition.getCodigo_modelo_a()));  // Corregido aquí
        }   
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        nombre_A = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();
        C_modelo = new javax.swing.JTextField();
        authorLbl = new javax.swing.JLabel();
        stock_L = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        titleLbl.setText("Nombre Accesorio ");

        nombre_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_AActionPerformed(evt);
            }
        });

        dateLbl.setText("Modelo Accesorio");

        C_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_modeloActionPerformed(evt);
            }
        });

        authorLbl.setText("Stock Accesorio");

        stock_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_LActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        button.setBackground(new java.awt.Color(0, 153, 51));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Añadir Accesorio");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Modelo");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(373, 373, 373))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stock_L, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(authorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(233, 233, 233))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                .addGap(234, 234, 234))
                            .addComponent(nombre_A, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(161, 161, 161))
                            .addComponent(C_modelo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(68, 68, 68)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_A, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(stock_L, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
         // Obtener el resto de los valores
    String nombre_model = nombre_A.getText();
    String code_model = C_modelo.getText();
    String stockL = stock_L.getText();
    String cod_mod = jTextField1.getText();

    // Validaciones para los campos
    if (nombre_model.isEmpty() || code_model.isEmpty() || stockL.isEmpty() || cod_mod.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);

        // Puedes establecer el foco en el campo que falta
        if (nombre_model.isEmpty()) {
            nombre_A.requestFocus();
        } else if (code_model.isEmpty()) {
            C_modelo.requestFocus();
        } else if (stockL.isEmpty()) {
            stock_L.requestFocus();
        } else if (cod_mod.isEmpty()) {
            // Establecer el foco en el campo de código modelo A
            jTextField1.requestFocus();
        }
        return;
    }

    // Crear un objeto Ficha_equipo con los datos obtenidos
    com.mycompany.models.Accesorio ficha = isEdition ? bookEdition : new com.mycompany.models.Accesorio();
    ficha.setNombre_accesorio(nombre_model);
    ficha.setCodigo_modelo(code_model);
    ficha.setCodigo_modelo_a(cod_mod);  // Cambiado aquí
    if (!stockL.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El campo de stock debe contener solo números. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        stock_L.requestFocus();
        return;
    }

    try {
    ficha.setStock_accesorio(Integer.parseInt(stockL));
} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "El campo de stock debe contener solo números. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
    stock_L.requestFocus();
    return;
}

    // Insertar en la base de datos
    try {
        DAOaccesorio dao = new DAOaccesorio_imple();

        if (!isEdition) {
            dao.registrar(ficha);
        } else {
            dao.modificar(ficha);
        }

        String successMsg = isEdition ? "modificada" : "registrada";

        javax.swing.JOptionPane.showMessageDialog(this, "Ficha " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        if (!isEdition) {
            // Limpiar campos después de la inserción
            nombre_A.setText("");
            C_modelo.setText("");
            stock_L.setText("");
            jTextField1.setText("");
        }
    } catch (Exception e) {
    String errorMsg = isEdition ? "modificar" : "registrar";
    javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " la ficha de equipo. \n" + e.getMessage(), "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();  // Imprimir la traza de la excepción
}
    System.out.println("Nombre: " + nombre_model + ", Código modelo: " + code_model + ", Stock: " + stockL + ", Código modelo A: " + cod_mod);
    
    }//GEN-LAST:event_buttonActionPerformed

    private void stock_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_LActionPerformed

    private void C_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_modeloActionPerformed

    private void nombre_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_AActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_modelo;
    private javax.swing.JLabel authorLbl;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nombre_A;
    private javax.swing.JTextField stock_L;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}